backend:
  name: github
  repo: ticketbutler/blog
 

media_folder: static/images
public_folder: images

collections:
  - name: blog
    label: Blog
    folder: /content
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Image, widget: image }
      - { name: author, label: Author }

